FROM eclipse-temurin:17-jdk

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        fontconfig \
        libfreetype6 \
        libxext6 \
        libxi6 \
        libxrender1 \
        libxtst6 \
    && rm -rf /var/lib/apt/lists/*

COPY scripts /usr/local/bin
RUN chmod +x /usr/local/bin/*.sh

CMD ["/usr/local/bin/dev-watch.sh"]
